//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public Venta()
        {
            this.Concepto = new HashSet<Concepto>();
        }
    
        public int idVenta { get; set; }
        public int idCliente { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<Concepto> Concepto { get; set; }
    }
}
